name: CI Pipeline GH
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  APPLICATION_FOLDER: demoSpringBoot
  AWS_REGION: us-east-1                             # ← Cambia por tu región
  S3_BUCKET: amazon-s3-valladares-github            # ← Cambia por tu bucket
  ARTIFACT_NAME: demoSpringBoot-0.0.1-SNAPSHOT.jar  # Nombre final del artifact

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build with Maven
        #working-directory: ${{ env.APPLICATION_FOLDER }}
        run: mvn clean package -DskipTests

      - name: Upload Artifact to S3
        #working-directory: ${{ env.APPLICATION_FOLDER }}/target
        working-directory: /target
        run: |
          aws s3 cp *.war s3://${{ env.S3_BUCKET }}/${{ env.ARTIFACT_NAME }} \
            --metadata CommitSha=${{ github.sha }}