name: CI Pipeline GH
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  APPLICATION_FOLDER: demoSpringBoot
  AWS_REGION: us-east-1                             # ← Cambia por tu región
  S3_BUCKET: amazon-s3-valladares-github            # ← Cambia por tu bucket
  ARTIFACT_NAME: demoSpringBoot-0.0.1-SNAPSHOT.jar  # Nombre final del artifact

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Maven Tests
        run: mvn clean test --no-transfer-progress

  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: List target directory
        run: ls -la target/
      # Subimos el artifact para que el siguiente job pueda usarlo
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target/*.jar
          #retention-days: 1

  upload-to-s3:
    name: Upload Artifact to S3
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: target
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload Artifact to S3
        run: |
          aws s3 cp target/*.jar \
            s3://${{ env.S3_BUCKET }}/${{ env.ARTIFACT_NAME }} \
            --metadata CommitSha=${{ github.sha }}deploy: